# -*- coding: utf-8 -*-
"""Day2_variables_input.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KvZpNuxZN8nQd5TFAABJCNn4JdWFFv-r
"""

name = "Alice"        # string
age = 25              # integer
height = 5.6          # float
is_coder = True       # boolean

print("Name:", name)
print("Age:", age)
print("Height:", height)
print("Is a coder?", is_coder)

# Finding Type
print (type(height))

# User input
your_name = input("What's your name?")
your_age = int (input("What's your age?"))

# Type conversion
# your_age = int(input("What's your age?")) # convert string to int,
# OR your_age = int(your_age)


print("Nice to meet you",your_name, "You'll be",your_age + 1, "next year.")