# -*- coding: utf-8 -*-
"""Ex. program for user input and mini calculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xXsfddkjl6kZf3FmYAxwW3NZ9IbesK_i
"""

# take user input and add 2 numbers
a = int (input ("Enter first number"))
b = int (input ("Enter second number"))
print (a+b)

# # input function returns user input as a string by default.

# # take user input and add 3 to the first number:

a= int (input ("Enter the first number"))
print (a+3)
# we cannot add string to the integer, only string and string can be added, so need to convert (a) into integer before adding 3.

# Build a Mini Calculator

a = int (input ("Enter first number"))
b = int (input ("Enter second number"))
c = input ("which operation: (+, -, *, /)")

if (c=="+"):
  print (a+b)
elif (c=="-"):
  print (a-b)
elif (c=="*"):
  print (a*b)
elif (c=="/"):
  print (a/b)
else:
  print ("operation invalid")