# -*- coding: utf-8 -*-
"""guessing_game_3_attempts

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17hXAhVPoYahYtOdWN88i1PoGrrdY1erg
"""

import random

print("Welcome to the Number Guessing Game!")
print("I'm thinking of a number between 1 and 10...")
print("You have 3 attempts to guess it!")

secret_number = random.randint(1, 10)
attempts = 3

while attempts > 0:
    guess = int(input(f"Attempt {4 - attempts}/3 - Take a guess: "))
    # or guess = int(input("Take a guess: "))

    if guess == secret_number:
        print("Correct! You guessed it!")
        break
    elif guess < secret_number:
        print("Too low!")
    else:
        print("Too high!")

    attempts -= 1

if attempts == 0:
    print("Out of attempts! The number was:", secret_number)