# -*- coding: utf-8 -*-
"""Loops_basics.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F5Vz41dcwpSQzueF4dv2jfpn8D1i76Sd
"""

# For loop: Print numbers 1 to 5
for i in range(1, 6):
    print("Number:", i)

# # While loop: Countdown
count = 5
while count > 0:
    print("Countdown:", count)
    count -= 1

# Using break and continue
for i in range(1, 10):
    if i == 5:
        print("i is:", i)
        break
    elif i == 3:
        continue
    print("i is:", i)