# -*- coding: utf-8 -*-
"""match_case_guessing_game.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zipkMms7yXuD6NZErruifVpmqn64lp6e
"""

a= int (input ("Ener any number between 1 to 100"))
match a:
  case 100:
    print("you won mobile phone")
  case 55:
    print("you won car")
  case _:
    print("better luck next time")