# -*- coding: utf-8 -*-
"""Number_guessing_game.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HFZve3loebyuSngnFEijzj3Q-xBwNXeb
"""

# Build a number guessing game using random numbers and if number is too high or low, show the answer
import random

print("Welcome to the Number Guessing Game!")
print("I'm thinking of a number between 1 and 10...")

secret_number = random.randint(1, 10)
guess = int(input("Take a guess: "))

if guess == secret_number:
    print("Correct! You guessed it!")
elif guess < secret_number:
  print("Too low! The number was", secret_number)
else:
    print("Too high! The number was", secret_number)