# -*- coding: utf-8 -*-
"""Password_checker.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f6PldTEI8m3z_3ss4-4vyaeL2EQfaS0U
"""

correct_password = "Jelly"
attempts = 3

while attempts > 0:
    guess = input(f"Attempt {4 - attempts}/3 - password: ")
    #or guess = input("Enter the password: ")
    if guess == correct_password:
        print("Access granted.")
        break
    else:
        print("Wrong password.")
        attempts -= 1

if attempts == 0:
    print("Access denied. You're locked out.")