# -*- coding: utf-8 -*-
"""PYTHON_Day 1_Hello_world.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mJ-MpvKmfkplE2t-WEG226lm2aQ-QK5_
"""

print ("Hello World, this is day 1 of my Python journey.")